import { StatusDTO } from "tweeter-shared";

export interface FeedStoryDTO {
  readonly alias: string;
  /** A string generated by concatenating the ISO date format of post
   * with the posting user alias. */
  readonly timestamp_unique: string;
  readonly status: StatusDTO;
}
